config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root 'welcome#index'
  resources :students
  resources :projects
  resources :courses
  resources :blogs
  resources :curriculums
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest user (not logged in)

    if user.teacher?
      can :read, Student
      # Add other permissions for teachers
    elsif user.principal?
      can :manage, :all
      # Add other permissions for principals
    end
  end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
  has_many :student_curriculums
  has_many :students, through: :student_curriculums
end

app/models/demo.rb
class Demo < ApplicationRecord
  belongs_to :student
  has_one :sub_demo
  before_create :greeting_message

  def greeting_message
    puts 'Hey! this will run before you create object'
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_one :manager
  has_one :manager_history, through: :manager
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :department
  has_one :manager_history
end

app/models/manager_history.rb
class ManagerHistory < ApplicationRecord
  belongs_to :manager
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_curriculums, dependent: :destroy
  has_many :curriculums, through: :student_curriculums
  validates :first_name, :last_name, :email, presence: true
  has_one_attached :profile_pic
  def self.ransackable_attributes(_auth_object = nil)
    %w[first_name]
  end
end

app/models/student_curriculum.rb
class StudentCurriculum < ApplicationRecord
  belongs_to :student
  belongs_to :curriculum
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :demo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  enum role: {teacher: 0, principal: 1}
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: %i[ show edit update destroy ]

  # GET /curriculums or /curriculums.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1 or /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums or /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to curriculum_url(@curriculum), notice: "Curriculum was successfully created." }
        format.json { render :show, status: :created, location: @curriculum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculums/1 or /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to curriculum_url(@curriculum), notice: "Curriculum was successfully updated." }
        format.json { render :show, status: :ok, location: @curriculum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1 or /curriculums/1.json
  def destroy
    @curriculum.destroy!

    respond_to do |format|
      format.html { redirect_to curriculums_url, notice: "Curriculum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curriculum_params
      params.require(:curriculum).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/curriculums/_curriculum.html.erb
<div id="<%= dom_id curriculum %>">
  <p>
    <strong>Name:</strong>
    <%= curriculum.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= curriculum.description %>
  </p>

</div>

app/views/curriculums/_form.html.erb
<%= form_with(model: curriculum) do |form| %>
  <% if curriculum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
        <% curriculum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing curriculum</h1>

<%= render "form", curriculum: @curriculum %>

<br>

<div>
  <%= link_to "Show this curriculum", @curriculum %> |
  <%= link_to "Back to curriculums", curriculums_path %>
</div>

app/views/curriculums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Curriculums</h1>

<div id="curriculums">
  <% @curriculums.each do |curriculum| %>
    <%= render curriculum %>
    <p>
      <%= link_to "Show this curriculum", curriculum %>
    </p>
  <% end %>
</div>

<%= link_to "New curriculum", new_curriculum_path %>

app/views/curriculums/new.html.erb
<h1>New curriculum</h1>

<%= render "form", curriculum: @curriculum %>

<br>

<div>
  <%= link_to "Back to curriculums", curriculums_path %>
</div>

app/views/curriculums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @curriculum %>

<div>
  <%= link_to "Edit this curriculum", edit_curriculum_path(@curriculum) %> |
  <%= link_to "Back to curriculums", curriculums_path %>

  <%= button_to "Destroy this curriculum", @curriculum, method: :delete %>
</div>